### ISSUE TITLE
ImportError: dynamic module does not define init function (initlibcudnn)

### ISSUE THREAD

**Issue by rolfvandam** [hannes-brt/cudnn-python-wrappers#10]
When I try to do `import libcudnn` I get the following error:

    ImportError: dynamic module does not define init function (initlibcudnn)

I'm running Ubuntu 14.10 and using cudnn-6.5-linux-x64-v2-rc2.

**Comment by hannes-brt** [comment]
I can't really tell what's going on unless you post the full traceback. `import libcudnn` works fine for me on Ubuntu 14.10 with cudnn v2 rc2, so there must be something else going on.

Make sure you're using the a version of `cudnn-python-wrappers` that is compatible with cudnn v2.

**Comment by rolfvandam** [comment]
It seems to be a problem with my cuda setup. It works fine now (but I switched to 14.04). 

That's the entry point by the way, one level up is just stdin (where I pasted the `import libcudnn`).
